version: '3.9'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: inundacion-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/backend
    depends_on:
      - database

  webserver:
    image: nginx:alpine
    container_name: inundacion-webserver
    ports:
      - "80:80"   # Accedes a Laravel desde http://localhost
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  database:
    image: mysql:8.0
    container_name: inundacion-db
    environment:
      MYSQL_DATABASE: monitoreo_inundaciones 
      MYSQL_USER: inundacion_user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword123
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      - --default-time-zone=+00:00
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  

volumes:
  db_data:
